const PAPERS = [
  {
    id:'rt2',
    title:'RT-2: Vision-Language-Action Models Transfer Web Knowledge to Robotic Control',
    authors:'Anthony Brohan, Noah Brown, Justice Carbajal, Yevgen Chebotar, Xi Chen, et al.',
    year:2023, venue:'CoRL / Google DeepMind',
    arxiv:'https://arxiv.org/abs/2307.15818',
    project:'https://robotics-transformer2.github.io/',
    tags:['VLA','Foundation Models','Manipulation'],
    emoji:'🤖',
    abstract:'提出将视觉-语言-动作统一为一个 Transformer，把来自互联网的视觉-语言知识迁移到机器人控制中，实现语义理解、推理和泛化到新物体/指令/场景。',
    why:'具身大模型里程碑：把机器人动作当成语言 token 输出，开启 VLA 范式。'
  },
  {
    id:'octo',
    title:'Octo: An Open-Source Generalist Robot Policy',
    authors:'Octo Model Team, Dibya Ghosh, Homer Walke, Karl Pertsch, et al.',
    year:2024, venue:'RSS / UC Berkeley',
    arxiv:'https://arxiv.org/abs/2405.12213',
    project:'https://octo-models.github.io/',
    tags:['VLA','Open-Source','Manipulation'],
    emoji:'🐙',
    abstract:'一个开源通用机器人策略，在跨多个 embodiment 的多源数据上预训练，可通过少量微调适配不同机械臂和任务，并支持目标图像与语言指令。',
    why:'开源版“通用机器人策略”，研究/复现的首选起点之一。'
  },
  {
    id:'openvla',
    title:'OpenVLA: An Open-Source Vision-Language-Action Model',
    authors:'Moo Jin Kim, Karl Pertsch, Siddharth Karamcheti, et al.',
    year:2024, venue:'CoRL / Stanford',
    arxiv:'https://arxiv.org/abs/2406.09246',
    project:'https://openvla.github.io/',
    tags:['VLA','Open-Source'],
    emoji:'🧠',
    abstract:'在 970k 真实机器人演示上训练的 7B 开源 VLA 模型，兼容 LLaMA-2 骨干，可微调用于不同机器人平台。',
    why:'当前最常用的开源 VLA 权重之一，便于做下游实验。'
  },
  {
    id:'pi0',
    title:'pi_0: A Vision-Language-Action Flow Model for General Robot Control',
    authors:'Physical Intelligence team',
    year:2024, venue:'Physical Intelligence',
    arxiv:'https://www.physicalintelligence.company/blog/pi0',
    project:'https://www.physicalintelligence.company/research/pi0',
    tags:['VLA','Flow Matching','Humanoid','Foundation Models'],
    emoji:'⚡',
    abstract:'基于 flow matching 的 VLA 模型，在多机器人、多任务数据上预训练，展示了跨形态通用控制和泛化能力。',
    why:'工业界 VLA 代表路线之一，动作流模型 + 大规模预训练。'
  },
  {
    id:'saycan',
    title:'Do As I Can, Not As I Say: Grounding Language in Robotic Affordances',
    authors:'Michael Ahn, Anthony Brohan, Noah Brown, Yevgen Chebotar, et al.',
    year:2022, venue:'CoRL / Google',
    arxiv:'https://arxiv.org/abs/2204.01691',
    project:'https://say-can.github.io/',
    tags:['LLM Agents','Planning','Manipulation'],
    emoji:'🗣️',
    abstract:'结合大语言模型做高层规划与价值函数做可行动性（affordance）评分，让语言指令在真实机器人场景中落地，完成长 horizon 厨房任务。',
    why:'LLM 作为机器人“大脑”的开山之作之一。'
  },
  {
    id:'rt1',
    title:'RT-1: Robotics Transformer for Real-World Control at Scale',
    authors:'Anthony Brohan, Noah Brown, Justice Carbajal, et al.',
    year:2022, venue:'RSS / Google',
    arxiv:'https://arxiv.org/abs/2212.06817',
    project:'https://robotics-transformer.github.io/',
    tags:['Behavior Cloning','Transformer','Manipulation'],
    emoji:'🦾',
    abstract:'大规模真实机器人数据训练的 Transformer 策略，在 130k 条演示上学习 700+ 任务，展示了数据驱动端到端控制的强大泛化。',
    why:'机器人 Transformer 大规模实证起点，奠定 RT 系列。'
  },
  {
    id:'diffusion_policy',
    title:'Diffusion Policy: Visuomotor Policy Learning via Action Diffusion',
    authors:'Chi Cheng, J. Zico Kolter, et al.',
    year:2023, venue:'RSS / Columbia',
    arxiv:'https://arxiv.org/abs/2303.04137',
    project:'https://diffusion-policy.cs.columbia.edu/',
    tags:['Manipulation','Diffusion','Imitation Learning'],
    emoji:'🌊',
    abstract:'将动作序列生成建模为扩散过程，在多种操作任务上取得优越的多模态动作建模表现与稳定性。',
    why:'扩散策略已成为机器人模仿学习的主流动作头之一。'
  },
  {
    id:'act',
    title:'Learning Fine-Grained Bimanual Manipulation with Low-Cost Hardware',
    authors:'Tony Z. Zhao, Vikash Kumar, Sergey Levine, Chelsea Finn',
    year:2023, venue:'RSS / Stanford',
    arxiv:'https://arxiv.org/abs/2306.15136',
    project:'https://tonyzhaozh.github.io/aloha/',
    tags:['Imitation Learning','Bimanual','Low-Cost Hardware'],
    emoji:'🥢',
    abstract:'通过动作分块（Action Chunking）与 Transformer，在低成本双臂 ALOHA 平台上学到精细操作，如穿电缆、开盖等。',
    why:'ACT/ALOHA 带动了低成本双臂遥操与精细操作研究热潮。'
  },
  {
    id:'aloha2',
    title:'ALOHA 2: A Low-Cost Bimanual Teleoperation System for Mobile Manipulation',
    authors:'Zipeng Fu, Tony Z. Zhao, Chelsea Finn',
    year:2024, venue:'arXiv / Stanford',
    arxiv:'https://aloha-2.github.io/',
    project:'https://aloha-2.github.io/',
    tags:['Bimanual','Mobile Manipulation','Hardware'],
    emoji:'🚪',
    abstract:'把 ALOHA 扩展到移动底盘，实现移动双臂操作，支持开抽屉、穿绳、开门等长时序任务。',
    why:'低成本 mobile manipulation 研究平台代表。'
  },
  {
    id:'droid',
    title:'DROID: A Large-Scale In-the-Wild Robot Manipulation Dataset',
    authors:'DROID dataset contributors (multiple institutions)',
    year:2024, venue:'CoRL',
    arxiv:'https://arxiv.org/abs/2403.12945',
    project:'https://droid-dataset.github.io/',
    tags:['Dataset','Manipulation','Multi-Setup'],
    emoji:'📦',
    abstract:'跨多个机构、多种机械臂/夹持器/场景采集的 76k+ 真实机器人操作轨迹数据集，含多视角 RGB-D 与语言指令。',
    why:'多实验室协作的“in-the-wild”真实数据集，泛化研究重要资源。'
  },
  {
    id:'openxembodiment',
    title:'Open X-Embodiment: Robotic Learning Datasets and RT-X Models',
    authors:'Open X-Embodiment Collaboration, Abhishek Padalkar, et al.',
    year:2023, venue:'ICRA / Google x Universities',
    arxiv:'https://arxiv.org/abs/2310.08864',
    project:'https://robotics-transformer-x.github.io/',
    tags:['Dataset','Multi-Embodiment','Foundation Models'],
    emoji:'🌍',
    abstract:'整合来自 22 个机构的机器人数据形成 Open X-Embodiment 数据集，并在其上训练跨 embodiment 的 RT-1-X / RT-2-X。',
    why:'跨形态机器人预训练的标志性数据+模型工作。'
  },
  {
    id:'tdmpc2',
    title:'TD-MPC2: Scalable, Robust World Models for Continuous Control',
    authors:'Nicklas Hansen, Hao Su, Xiaolong Wang',
    year:2024, venue:'ICML',
    arxiv:'https://arxiv.org/abs/2310.16828',
    project:'https://www.tdmpc2.com/',
    tags:['World Model','RL','Locomotion','Manipulation'],
    emoji:'🌐',
    abstract:'大规模世界模型 + MPC 规划的强化学习框架，单套超参在 DMControl / Meta-World / ManiSkill 等众多任务上取得强结果。',
    why:'可扩展世界模型 RL 代表，兼具样本效率与通用性。'
  },
  {
    id:'dreamerv3',
    title:'Mastering Diverse Domains through World Models',
    authors:'Danijar Hafner, Jurgis Pasukonis, Jimmy Ba, Timothy Lillicrap',
    year:2023, venue:'ICML',
    arxiv:'https://arxiv.org/abs/2301.04104',
    project:'https://danijar.com/project/dreamerv3/',
    tags:['World Model','RL','General'],
    emoji:'💭',
    abstract:'提出 DreamerV3，一个通用的基于世界模型的 RL 算法，在视觉连续控制、Atari、MineCraft 等多域以固定超参学习。',
    why:'世界模型路线的标杆，推动“通用 agent”讨论。'
  },
  {
    id:'mujoco_menagerie',
    title:'MuJoCo Menagerie: High-quality simulation models for robotics',
    authors:'Google DeepMind contributors',
    year:2022, venue:'Open Source',
    arxiv:'https://github.com/google-deepmind/mujoco_menagerie',
    project:'https://mujoco.org/',
    tags:['Simulator','Hardware Models'],
    emoji:'🧰',
    abstract:'开源高质量 MuJoCo 机器人模型集合，覆盖主流机械臂、人形、四足等。',
    why:'做 sim 实验/人形控制的“模型仓库”必需品。'
  },
  {
    id:'habitat3',
    title:'Habitat 3.0: A Co-Habitat for Humans, Avatars and Robots',
    authors:'Santhosh K. Ramakrishnan, Xavier Puig, et al.',
    year:2023, venue:'ICRA / Meta FAIR',
    arxiv:'https://arxiv.org/abs/2310.13724',
    project:'https://aihabitat.org/habitat3/',
    tags:['Simulator','Navigation','Human-Robot Interaction','Home'],
    emoji:'🏠',
    abstract:'支持人形机器人与人化身在真实家居场景中交互的仿真平台，面向社交导航、协作与 household 任务。',
    why:'人机同环境交互仿真的代表性平台。'
  },
  {
    id:'isaaclab',
    title:'Isaac Lab: A Unified and Modular Framework for Robot Learning in Simulation',
    authors:'NVIDIA contributors',
    year:2024, venue:'Open Source / NVIDIA',
    arxiv:'https://isaac-sim.github.io/IsaacLab/',
    project:'https://isaac-sim.github.io/IsaacLab/',
    tags:['Simulator','GPU Parallelism','RL','Humanoid'],
    emoji:'🚀',
    abstract:'基于 Isaac Sim 的统一化机器人学习框架，支持大规模并行仿真与 RL/模仿学习，覆盖机械臂、四足、人形等。',
    why:'当前 GPU 并行仿真与大规模 RL 的主流框架之一。'
  },
  {
    id:'maniskill2',
    title:'ManiSkill2: A Unified Benchmark for Generalizable Manipulation Skills',
    authors:'Tongzhou Mu, Ruihan Yang, et al.',
    year:2023, venue:'ICLR / UCSD',
    arxiv:'https://arxiv.org/abs/2302.04659',
    project:'https://maniskill2.github.io/',
    tags:['Simulator','Manipulation','Benchmark'],
    emoji:'🎛️',
    abstract:'提供大量可泛化的操作任务与并行渲染，支持从点云/视觉输入进行模仿与强化学习，配套评测基准。',
    why:'操作 sim benchmark 的重要选择。'
  },
  {
    id:'robosuite',
    title:'robosuite: A Modular Simulation Framework and Benchmark for Robot Learning',
    authors:'Yuke Zhu, Josiah Wong, et al.',
    year:2020, venue:'NeurIPS Datasets and Benchmarks / UT Austin',
    arxiv:'https://arxiv.org/abs/2009.12293',
    project:'https://robosuite.ai/',
    tags:['Simulator','Manipulation','Benchmark'],
    emoji:'🧪',
    abstract:'基于 MuJoCo 的模块化机器人操作仿真框架，提供多机械臂、多任务与可组合场景。',
    why:'学术圈常用的干净、可扩展操作仿真框架。'
  },
  {
    id:'metaworld',
    title:'Meta-World: A Benchmark and Evaluation for Multi-Task and Meta RL',
    authors:'Tianhe Yu, Deirdre Quillen, Zhanpeng He, Ryan Julian, et al.',
    year:2019, venue:'CoRL / Stanford',
    arxiv:'https://arxiv.org/abs/1910.10897',
    project:'https://meta-world.github.io/',
    tags:['Benchmark','RL','Manipulation','Multi-Task'],
    emoji:'🧩',
    abstract:'包含 50 个不同操作任务的多任务/元强化学习基准，评估任务泛化与组合。',
    why:'多任务机器人 RL 的经典基准。'
  },
  {
    id:'rlbench',
    title:'RLBench: The Robot Learning Benchmark & Learning Environment',
    authors:'Stephen James, Zicong Ma, David Rovick Arrojo, Andrew J. Davison',
    year:2020, venue:'RA-L / ICRA',
    arxiv:'https://arxiv.org/abs/1909.12271',
    project:'https://sites.google.com/view/rlbench',
    tags:['Benchmark','Simulator','Manipulation'],
    emoji:'🔩',
    abstract:'基于 CoppeliaSim 的 100+ 操作任务学习基准，提供多视角观测、稠密 reward 与标准化评估。',
    why:'早期视觉操作 benchmark 之一，催生大量工作。'
  },
  {
    id:'pointnav',
    title:'PointGoal Navigation: DD-PPO / Habitat baselines',
    authors:'Dhruv Batra, Angel X. Chang, et al. (Habitat team)',
    year:2019, venue:'ICCV / Meta FAIR',
    arxiv:'https://arxiv.org/abs/1904.01201',
    project:'https://aihabitat.org/',
    tags:['Navigation','Embodied Vision'],
    emoji:'🧭',
    abstract:'在逼真 3D 家居扫描中以相对目标点为目标的视觉导航基准与强基线代理。',
    why:'Embodied AI 导航任务的事实标准起点。'
  },
  {
    id:'objectnav',
    title:'ObjectGoal Navigation in Habitat / RoboTHOR',
    authors:'FAIR Habitat, Allen Institute, et al.',
    year:2020, venue:'CVPR Embodied AI Workshop',
    arxiv:'https://arxiv.org/abs/2006.13171',
    project:'https://aihabitat.org/challenge/2020/',
    tags:['Navigation','Semantic','Embodied Vision'],
    emoji:'🔎',
    abstract:'以“找到某个类别物体”为目标的语义导航基准，在 Habitat 等环境中推动了语义探索/建图研究。',
    why:'语义导航与 embodied question answering 的重要基础。'
  },
  {
    id:'semexp',
    title:'Semantic Curiosity for Active Visual Learning',
    authors:'Devendra Singh Chaplot, et al.',
    year:2020, venue:'ECCV',
    arxiv:'https://arxiv.org/abs/2008.08580',
    project:'https://devendrachaplot.github.io/projects/semantic-curiosity',
    tags:['Navigation','Exploration','Semantic'],
    emoji:'🗺️',
    abstract:'构建语义地图并基于语义好奇心引导探索，在 ObjectNav 等任务中提升探索效率。',
    why:'经典“显式地图 + 语义”导航范式代表。'
  },
  {
    id:'vim4ab',
    title:'VIMA: General Robot Manipulation with Multimodal Prompts',
    authors:'Yunfan Jiang, Agrim Gupta, Zichen Zhang, et al.',
    year:2022, venue:'ICML / Stanford + NVIDIA',
    arxiv:'https://arxiv.org/abs/2210.03094',
    project:'https://vimalabs.github.io/',
    tags:['Multimodal','Manipulation','Prompting'],
    emoji:'🎨',
    abstract:'支持以图像、文本、视频演示等多模态 prompt 为条件的通用操作策略，展示多任务条件控制与泛化。',
    why:'多模态指令驱动操作的代表作。'
  },
  {
    id:'vil2l',
    title:'VIOLA: Imitation Learning for Vision-Based Manipulation with Object-Centric Keypoints',
    authors:'Yifeng Zhu, Abhishek Joshi, Peter Stone, Yuke Zhu',
    year:2022, venue:'CoRL',
    arxiv:'https://arxiv.org/abs/2205.12953',
    project:'https://ut-austin-rpl.github.io/VIOLA/',
    tags:['Imitation Learning','Object-Centric','Manipulation'],
    emoji:'🔑',
    abstract:'基于物体中心点表示和 Transformer 策略，从少量演示学习长 horizon 操作任务。',
    why:'物体结构归纳偏置 + IL 的优秀实践。'
  },
  {
    id:'nerfmm',
    title:'iNeRF: Inverting Neural Radiance Fields for Pose Estimation',
    authors:'Lin Yen-Chen, Pete Florence, Jonathan T. Barron, Alberto Rodriguez, Phillip Isola, Tsung-Yi Lin',
    year:2020, venue:'CoRL',
    arxiv:'https://arxiv.org/abs/2012.05877',
    project:'https://yenchenlin.me/inerf/',
    tags:['Perception','NeRF','Pose Estimation'],
    emoji:'✨',
    abstract:'通过 NeRF 反向求解相机位姿，可用于机器人 6DoF 物体定位与抓取等。',
    why:'NeRF 与具身感知结合的早期代表，启发后续 NeRF for robotics。'
  },
  {
    id:'lerobot',
    title:'LeRobot: Machines That Learn in the Real World',
    authors:'Hugging Face LeRobot team',
    year:2024, venue:'Open Source / Hugging Face',
    arxiv:'https://github.com/huggingface/lerobot',
    project:'https://huggingface.co/lerobot',
    tags:['Open-Source','VLA','Dataset','Low-Cost Hardware'],
    emoji:'🤗',
    abstract:'Hugging Face 开源机器人学习框架，含数据集格式、ACT/Diffusion/VLA 模型、低成本机械臂教程与预训练权重。',
    why:'对入门者极为友好，集数据/训练/部署一体。'
  },
  {
    id:'lerobot_so100',
    title:'SO-100: A Low-Cost 3D-Printable Robot Arm for Research and Education',
    authors:'LeRobot contributors',
    year:2024, venue:'Hugging Face / Open Hardware',
    arxiv:'https://github.com/huggingface/lerobot',
    project:'https://lerobot.com/',
    tags:['Hardware','Low-Cost','Open-Source'],
    emoji:'🦾',
    abstract:'廉价 3D 打印机械臂参考设计与驱动栈，适配 LeRobot 框架可训练端到端策略。',
    why:'让“一个人也能做具身 AI 实验”的硬件基础。'
  },
  {
    id:'graspnet',
    title:'6-DoF GraspNet: Variational Grasp Generation for Object Manipulation',
    authors:'Arsalan Mousavian, Clemens Eppner, Dieter Fox',
    year:2019, venue:'ICCV / NVIDIA',
    arxiv:'https://arxiv.org/abs/1905.10520',
    project:'https://research.nvidia.com/publication/2019-10_6-dof-graspnet',
    tags:['Grasping','Perception'],
    emoji:'✊',
    abstract:'在点云上生成 6-DoF 抓取姿态并通过 evaluator 选优，是通用抓取检测重要基线。',
    why:'6DoF 抓取网络的经典之作。'
  },
  {
    id:'contact_graspnet',
    title:'Contact-GraspNet: Efficient 6-DoF Grasp Generation in Cluttered Scenes',
    authors:'Martin Sundermeyer, Arsalan Mousavian, Rudolph Triebel, Dieter Fox',
    year:2021, venue:'ICRA / NVIDIA',
    arxiv:'https://arxiv.org/abs/2103.14127',
    project:'https://research.nvidia.com/publication/2021-05_contact-graspnet',
    tags:['Grasping','Perception','Clutter'],
    emoji:'🧲',
    abstract:'直接从场景点云中预测接触点的抓取方法，在杂乱场景中速度快且效果强。',
    why:'实用型抓取姿态生成的热门基线。'
  },
  {
    id:'anygrasp',
    title:'AnyGrasp: Robust, Efficient, and General Grasp Perception',
    authors:'Hao-Shu Fang, et al.',
    year:2023, venue:'ICRA / Tsinghua',
    arxiv:'https://arxiv.org/abs/2212.08333',
    project:'https://graspnet.net/anygrasp.html',
    tags:['Grasping','Universal'],
    emoji:'🤏',
    abstract:'号称“通用抓取感知”，在大量 RGBD 数据上训练，适用于未见物体、开放场景。',
    why:'业界落地常用的通用抓取感知模型之一。'
  },
  {
    id:'voxposer',
    title:'VoxPoser: Composable 3D Value Maps for Robotic Manipulation with Language Models',
    authors:'Wenlong Huang, Chen Wang, Ruohan Zhang, Yunzhu Li, Jiajun Wu, Li Fei-Fei',
    year:2023, venue:'CoRL / Stanford',
    arxiv:'https://arxiv.org/abs/2307.05973',
    project:'https://voxposer.github.io/',
    tags:['LLM Agents','3D Perception','Planning'],
    emoji:'🧱',
    abstract:'LLM 生成 Python 代码来组合 3D 体素价值地图（可利用视觉基础模型能力），指导机器人完成开放词汇操作。',
    why:'代码/体素作为接口连接 LLM 与机器人的经典思路。'
  },
  {
    id:'code_as_policies',
    title:'Code as Policies: Language Model Programs for Embodied Control',
    authors:'Jacky Liang, Wenlong Huang, Fei Xia, Peng Xu, Karol Hausman, Brian Ichter, et al.',
    year:2022, venue:'ICRA / Google',
    arxiv:'https://arxiv.org/abs/2209.07753',
    project:'https://code-as-policies.github.io/',
    tags:['LLM Agents','Code Generation','Manipulation'],
    emoji:'💻',
    abstract:'让 LLM 直接生成机器人 API 调用代码作为策略，可组合感知与控制 primitives 完成多步任务。',
    why:'“LLM 写程序控制机器人”的代表作。'
  },
  {
    id:'inner_monologue',
    title:'Inner Monologue: Embodied Reasoning through Planning with Language Models',
    authors:'Wenlong Huang, Fei Xia, Ted Xiao, Harris Chan, Jacky Liang, et al.',
    year:2022, venue:'CoRL / Google',
    arxiv:'https://arxiv.org/abs/2207.05608',
    project:'https://innermonologue.github.io/',
    tags:['LLM Agents','Closed-Loop Planning'],
    emoji:'🗨️',
    abstract:'通过环境反馈让 LLM 进行闭环规划，在指令下完成多步机器人操作，具备失败检测与重新规划能力。',
    why:'“内心独白”式闭环推理经典工作。'
  },
  {
    id:'progprompt',
    title:'ProgPrompt: Generating Situated Robot Task Programs Using Large Language Models',
    authors:'Ishika Singh, Valts Blukis, Arsalan Mousavian, et al.',
    year:2022, venue:'ICRA / NVIDIA',
    arxiv:'https://arxiv.org/abs/2212.10036',
    project:'https://progprompt.github.io/',
    tags:['LLM Agents','Program Synthesis'],
    emoji:'📝',
    abstract:'使用 LLM 基于场景上下文（物体/动作空间）生成可执行机器人任务程序。',
    why:'场景条件化程序合成方向代表作。'
  },
  {
    id:'llm_planner',
    title:'LLM+P: Empowering Large Language Models with Optimal Planning Proficiency',
    authors:'Bo Liu, Yuqian Jiang, et al.',
    year:2023, venue:'IJCAI',
    arxiv:'https://arxiv.org/abs/2304.11477',
    project:'https://cocosci-principles.github.io/llm-p/',
    tags:['LLM Agents','Classical Planning','Hybrid'],
    emoji:'🧮',
    abstract:'让 LLM 用自然语言生成 PDDL 域/问题再交给经典规划器求解，兼具语言理解与可证明规划能力。',
    why:'LLM+符号规划器混合方案的代表。'
  },
  {
    id:'voyager',
    title:'Voyager: An Open-Ended Embodied Agent with Large Language Models (Minecraft)',
    authors:'Guanzhi Wang, Yuqi Xie, et al.',
    year:2023, venue:'NeurIPS / NVIDIA',
    arxiv:'https://arxiv.org/abs/2305.16291',
    project:'https://voyager.minedojo.org/',
    tags:['LLM Agents','Open-Ended','Skill Library'],
    emoji:'⛏️',
    abstract:'在 Minecraft 中由 LLM 驱动的终身学习 agent，能自动写代码、构建技能库并探索。',
    why:'开放世界具身智能的经典案例，对机器人“技能库”有启发。'
  },
  {
    id:'mineclip',
    title:'MineCLIP: Foundation Model for Minecraft Agents',
    authors:'William H. Guss, et al.',
    year:2022, venue:'NeurIPS',
    arxiv:'https://arxiv.org/abs/2206.08953',
    project:'https://mineclip.fandom.ai/',
    tags:['Multimodal','Embodied Agents','Minecraft'],
    emoji:'🎮',
    abstract:'在大量 Minecraft 视频-字幕对上对比学习的基础模型，可用于奖励塑造与任务条件控制。',
    why:'游戏具身方向重要基础模型。'
  },
  {
    id:'humanoid_bench',
    title:'HumanoidBench: Simulated Humanoid Benchmark for Whole-Body Locomotion and Manipulation',
    authors:'Carmelo Sferrazza, et al.',
    year:2024, venue:'RSS / UC Berkeley',
    arxiv:'https://arxiv.org/abs/2403.13036',
    project:'https://humanoid-bench.github.io/',
    tags:['Humanoid','Benchmark','Whole-Body Control'],
    emoji:'🏃',
    abstract:'面向人形机器人的全身控制基准，覆盖 locomotion + manipulation 任务，基于 Isaac/IsaacLab。',
    why:'人形大热时期非常好用的 sim benchmark。'
  },
  {
    id:'unitree_g1',
    title:'Learning Humanoid Locomotion with Reinforcement Learning (Unitree G1 public demos)',
    authors:'Unitree Robotics, various collaborators',
    year:2024, venue:'Industry / Open demos',
    arxiv:'https://www.unitree.com/g1',
    project:'https://www.unitree.com/g1',
    tags:['Humanoid','Hardware','Locomotion'],
    emoji:'🧍',
    abstract:'结合 Isaac 大规模并行 sim + RL 训练的人形 locomotion 展示，推动人形从“传统控制”走向“学习控制”热潮。',
    why:'人形 RL locomotion 工业化的代表性案例。'
  },
  {
    id:'gpt4_robot_demo',
    title:'GPT-4 Robotics Research Preview (Microsoft / OpenAI)',
    authors:'Microsoft Autonomous Systems and Robotics Research',
    year:2023, venue:'Tech Report',
    arxiv:'https://www.microsoft.com/en-us/research/uploads/prod/2023/02/ChatGPT_Robotics.pdf',
    project:'https://github.com/microsoft/autogen',
    tags:['LLM Agents','Multimodal'],
    emoji:'🧑‍💻',
    abstract:'探索使用多模态 LLM（含视觉）直接做机器人任务规划、错误恢复与 API 调用。',
    why:'多模态大模型用于机器人的高关注探索。'
  },
  {
    id:'3d_diffuser_actor',
    title:'3D Diffuser Actor: Policy Diffusion on 3D Tokens',
    authors:'Muhammad Zubair Irshad, et al.',
    year:2024, venue:'CoRL / FAIR',
    arxiv:'https://arxiv.org/abs/2402.10885',
    project:'https://3d-diffuser-actor.github.io/',
    tags:['3D Perception','Diffusion','Manipulation'],
    emoji:'🧊',
    abstract:'在 3D 体素/特征上做扩散动作预测，结合几何归纳取得强操作表现。',
    why:'3D 表示 + Diffusion policy 新趋势代表。'
  },
  {
    id:'robocasa',
    title:'RoboCasa: Large-Scale Simulation of Everyday Tasks for Generalist Robots',
    authors:'Yuke Zhu et al. (UT Austin / TIAGo)',
    year:2024, venue:'RSS',
    arxiv:'https://arxiv.org/abs/2406.02523',
    project:'https://robocasa.ai/',
    tags:['Simulator','Home','Manipulation','Benchmark'],
    emoji:'🍳',
    abstract:'面向家庭日常任务的大规模仿真基准，包含大量程序化生成场景与家居任务。',
    why:'家居操作 sim 方向的新重要资源。'
  },
  {
    id:'robomimic',
    title:'RoboMimic: A Framework for Robot Learning from Demonstration',
    authors:'Ajay Mandlekar, Danfei Xu, Roberto Martin-Martin, Yuke Zhu, Li Fei-Fei, Silvio Savarese',
    year:2021, venue:'NeurIPS D&B / Stanford',
    arxiv:'https://arxiv.org/abs/2108.03298',
    project:'https://robomimic.github.io/',
    tags:['Imitation Learning','Benchmark','Framework'],
    emoji:'📚',
    abstract:'标准化的模仿学习框架与基准，支持多种算法（BC, BC-RNN, CQL, IQL 等）与真实/仿真数据。',
    why:'做模仿学习对比实验的“标配”框架。'
  },
  {
    id:'bridge_data_v2',
    title:'BridgeData V2: A Dataset for Robot Learning at Scale',
    authors:'Homer Walke, Kevin Black, et al.',
    year:2023, venue:'CoRL / UC Berkeley',
    arxiv:'https://arxiv.org/abs/2308.12952',
    project:'https://rail-berkeley.github.io/bridgedata/',
    tags:['Dataset','Manipulation','Open-Source'],
    emoji:'🌉',
    abstract:'多场景、多任务、widowX 机械臂的真实机器人演示数据集，开源可下载，广泛用于研究。',
    why:'Berkeley 真实机器人数据生态的核心数据集。'
  },
  {
    id:'libero',
    title:'LIBERO: A Robotics Benchmark for Lifelong Learning (Continual Manipulation)',
    authors:'Bo Liu, Yifeng Zhu, et al.',
    year:2023, venue:'NeurIPS',
    arxiv:'https://arxiv.org/abs/2306.03310',
    project:'https://libero-robot.github.io/',
    tags:['Benchmark','Lifelong Learning','Manipulation'],
    emoji:'📖',
    abstract:'面向终身/连续学习的视觉操作基准，包含按主题组织的任务序列，评估知识保留与迁移。',
    why:'研究“持续学习+机器人”少有的标准化基准。'
  },
  {
    id:'calvin',
    title:'CALVIN: A Benchmark for Long-Horizon Language-Conditioned Robot Tasks',
    authors:'Oier Mees, Lukas Hermann, Erick Rosete-Beas, Wolfram Burgard',
    year:2022, venue:'CoRL',
    arxiv:'https://arxiv.org/abs/2112.03227',
    project:'https://calvin.cs.uni-freiburg.de/',
    tags:['Benchmark','Language-Conditioned','Long Horizon'],
    emoji:'🔗',
    abstract:'在真实桌面环境中采集的语言条件长时序操作基准，支持 zero-shot 任务组合评测。',
    why:'语言条件长 horizon 操作的重要开源基准。'
  },
  {
    id:'shadowhand',
    title:'Learning Dexterous In-Hand Manipulation (OpenAI Shadow Hand)',
    authors:'OpenAI (Bowen Baker, et al.)',
    year:2019, venue:'OpenAI',
    arxiv:'https://arxiv.org/abs/1808.00177',
    project:'https://openai.com/index/learning-dexterity/',
    tags:['Dexterous Manipulation','RL','Sim2Real'],
    emoji:'🖐️',
    abstract:'使用大规模并行仿真 + RL + 域随机化，在 Shadow Hand 上学习灵巧的手内操纵。',
    why:'深度 RL + sim2real 的经典震撼之作。'
  },
  {
    id:'sim2real_survey',
    title:'Sim-to-Real Transfer in Robotics: A Survey',
    authors:'Wenshuai Zhao, et al.',
    year:2022, venue:'Survey',
    arxiv:'https://arxiv.org/abs/2206.05922',
    project:null,
    tags:['Sim2Real','Survey'],
    emoji:'🔁',
    abstract:'系统梳理 sim2real 的域随机化、域适应、系统辨识、可微仿真等技术路线。',
    why:'快速入门 sim2real 全貌的综述。'
  },
  {
    id:'embodied_ai_survey',
    title:'Embodied AI: A Survey',
    authors:'Jinghuan Shang, et al.',
    year:2024, venue:'Survey',
    arxiv:'https://arxiv.org/abs/2403.02633',
    project:null,
    tags:['Survey','Foundation Models'],
    emoji:'📜',
    abstract:'从感知、导航、操作、交互、基础模型等角度综述具身智能研究全景。',
    why:'想搭知识地图？先读这篇。'
  },
  {
    id:'vlm_robotics_survey',
    title:'A Survey on Vision-Language Models for Robotics',
    authors:'Multiple authors',
    year:2024, venue:'Survey',
    arxiv:'https://arxiv.org/abs/2404.14488',
    project:null,
    tags:['Survey','VLA','LLM Agents'],
    emoji:'📘',
    abstract:'综述 VLM/LLM 在机器人感知、规划、控制中的角色划分与代表方法。',
    why:'从 LLM/VLM 视角看具身 AI 的体系化综述。'
  }
];

// 每日主题轮换（用于英雄卡排序与推荐理由）
const DAILY_THEMES = [
  {tag:'VLA', title:'视觉-语言-动作 (VLA) 大模型', hook:'从 RT-2 到 pi_0：让机器人读懂世界并行动。'},
  {tag:'Simulator', title:'仿真平台与大规模并行', hook:'好仿真决定了学习算法的上限。'},
  {tag:'Manipulation', title:'机械臂操作', hook:'抓取、插拔、双手协作：操作能力如何走向通用。'},
  {tag:'Diffusion', title:'扩散策略与生成式控制', hook:'把动作当作生成内容，多模态轨迹变得更自然。'},
  {tag:'LLM Agents', title:'LLM 驱动的具身智能体', hook:'让大模型做规划、写代码、当机器人大脑。'},
  {tag:'Humanoid', title:'人形机器人', hook:'人形硬件 + 学习控制的复兴之年。'},
  {tag:'Dataset', title:'具身数据集', hook:'数据是基石，看看哪些 dataset 在推动领域。'},
  {tag:'Navigation', title:'导航与探索', hook:'从 PointNav 到语义导航，智能体如何在空间中行走？'},
  {tag:'Imitation Learning', title:'模仿学习', hook:'用演示学策略，仍是最实用的落地路径之一。'},
  {tag:'Grasping', title:'通用抓取', hook:'未见物体也能稳准地抓起来？'},
  {tag:'Benchmark', title:'评测基准', hook:'怎么公平地比？聊聊重要 benchmark。'},
  {tag:'Open-Source', title:'开源生态', hook:'从 LeRobot 到 Octo/OpenVLA，开源如何改变领域。'},
  {tag:'Survey', title:'综述与路线图', hook:'快速建立领域图景的日子。'},
  {tag:'World Model', title:'世界模型', hook:'学一个“世界模拟器”，再在里面做规划。'}
];
